### PR TITLE
(fix) Bump remove_dir_all to 0.8.2

### PR DESCRIPTION
**Pull request by barathrm**
Old version has a listed security vuln.

Fixes
```
Crate:     remove_dir_all
Version:   0.6.1
Title:     Race Condition Enabling Link Following and Time-of-check Time-of-use (TOCTOU)
Date:      2023-02-24
ID:        RUSTSEC-2023-0018
URL:       https://rustsec.org/advisories/RUSTSEC-2023-0018
Solution:  Upgrade to >=0.8.0
Dependency tree:
remove_dir_all 0.6.1
└── etebase 0.5.3
```

### CODE REVIEW

**Review by Xiretza — APPROVED** [review]
Looks like remove_dir_all doesn't really follow semver, there were no breaking changes between 0.6.1 and 0.8.0 that I can find. So a pure bump without changing any code should be fine.

**Comment by tasn** [comment]
CI is failing.

**Comment by barathrm** [comment]
Cargo build succeeded locally, but the test fails with not finding version 0.8.0 of remove_dir_all. Trying with 0.8.2.

**Comment by tasn** [comment]
I think you have a typo? You added a `v`

**Comment by barathrm** [comment]
Yep, fixed :facepalm:

**Comment by tasn** [comment]
Still failing. :|

**Comment by barathrm** [comment]
> Still failing. :|

Hm. Seems like the part that's failing is the test running cargo with rust nightly and `-Z minimal-versions`. I can look into why that might fail (a quick read of [the docs](https://doc.rust-lang.org/nightly/cargo/reference/unstable.html#minimal-versions) (?) doesn't really help me), but if someone knows that'd be a nice short-cut. xD

**Comment by tasn** [comment]
There are also unrelated clippy errors (I guess because we are using a new enough clippy) which will just be fixed with `clippy --fix` ,but probably deserve a new PR. Would be great if you could do that too, though otherwise I can quickly do it myself. LMK.

**Comment by barathrm** [comment]
Running the nightly toolchain locally with `cargo generate-lockfile -Z minimal-versions` works fine for me. A bit of googling indicates that this kind of thing *might* happen if cargo uses a cache to look up dependencies?

**Comment by barathrm** [comment]
The failing test workflow which should run rust nightly (?) says

> rustc 1.68.2 (9eb3afe9e 2023-03-27)

However, when I install nightly locally I get 

> rustc 1.70.0-nightly (af06dce64 2023-04-08)

**Comment by barathrm** [comment]
> There are also unrelated clippy errors (I guess because we are using a new enough clippy) which will just be fixed with `clippy --fix` ,but probably deserve a new PR. Would be great if you could do that too, though otherwise I can quickly do it myself. LMK.

Attempt here https://github.com/etesync/etebase-rs/pull/43

**Comment by Xiretza** [comment]
Nightly is only used to generate the minimal-versions lockfile, the tests themselves run with the Minimum Supported Rust Version (1.68). Maybe remove_dir_all 0.8.0 requires a newer MSRV?

**Comment by tasn** [comment]
@barathrm, I merged your other PR, please rebase this on top of that so clippy is fixed. :)

**Comment by tasn** [comment]
I think @Xiretza is right. We can update the min rust version for all I care. I didn't even remember we set one.

**Comment by barathrm** [comment]
> Nightly is only used to generate the minimal-versions lockfile, the tests themselves run with the Minimum Supported Rust Version (1.56). Maybe remove_dir_all 0.8.0 requires a newer MSRV?

You're right, I can reproduce the issue locally by manually using 1.56.0. Gonna try bumping to something newer.

**Comment by barathrm** [comment]
Not sure why the minimal versions workflow fails on openssl now... can't reproduce that locally, and the docker does have libssl-dev installed.

**Comment by tasn** [comment]
No idea. :|

**Comment by Xiretza** [comment]
Wild guess: the container image has updated/changed at some point and now contains an incompatible openssl version?

**Comment by barathrm** [comment]
> Wild guess: the container image has updated/changed at some point and now contains an incompatible openssl version?

Hm, maybe. Or the versions selected by rust nightly's -Z minimal-versions aren't compatible with the docker's openssl?

Seems like the workflow uses [ubuntu-latest](https://github.com/etesync/etebase-rs/blob/master/.github/workflows/test.yml#L16), which I assume is the default github ubuntu latest docker.

**Comment by Xiretza** [comment]
> Hm, maybe. Or the versions selected by rust nightly's -Z minimal-versions aren't compatible with the docker's openssl?

Those shouldn't have changed since the last time CI ran (successfully).

> Seems like the workflow uses [ubuntu-latest](https://github.com/etesync/etebase-rs/blob/master/.github/workflows/test.yml#L16), which I assume is the default github ubuntu latest docker.

It's probably that then - ubuntu-latest always points at the latest release, which can and will change. Looks like it updated to openssl 3.x, which isn't supported by openssl-sys 0.9.55: https://stackoverflow.com/questions/67346713/wsl-ubuntu-cargo-rust-openssl-environment-variables-not-set

**Comment by tasn** [comment]
Should we just bump openssl-sys?

**Comment by barathrm** [comment]
Well then. bumped openssl-sys, openssl and cc. Had to bump cc to be able to build the newer openssl-sys, as mentioned in the commit msg. Tests pass.

**Pull request merged**
