### PR TITLE
Run tests in CI, against a test server

### PR DESCRIPTION
**Pull request by djmitche**
Similar to #14, but this will require more work on the tests as they currently embed expectations about the server.

### CODE REVIEW

**Comment by djmitche** [comment]
@tasn this might require that you enable actions on this repo?

**Comment by djmitche** [comment]
Hah, I meant similar to https://github.com/etesync/etebase-go/pull/14!  But it's also related to #14 in this repo.

**Comment by djmitche** [comment]
I've updated the test suite to signup the user before trying to reset it, ignoring conflicts.  That gets most of the tests passing, but four are still failing.  Let's get actions working on this repo, and see if that reproduces in CI.  If so, perhaps I can get a hand at what is causing those failures: are those tests just broken (do they pass for you, @tasn)? are they expecting a feature not in the 0.7.0 release of etesync-server?  have I missed some other subtlety of setting up the test server?

**Comment by tasn** [comment]
I think the server post-0.7.0 may have added some things. Which is another reason to why I think the test images should be based on master rather than versioned and matching the previous release. :)

**Comment by tasn** [comment]
Actions are enabled for this repo (I just checked). I think that maybe Github is clamping down on actions in pull requests because they were used by crypto miner. Maybe that's what's going on.

**Comment by djmitche** [comment]
It might be that they don't run on PRs until they're merged to the default branch.  I'll make another go at this PR, and then maybe yo can merge and we can address any failures in the action in another PR?

**Comment by tasn** [comment]
Yeah, I'm fine with that. Just let's wait on the latest docker image to be out.

**Comment by djmitche** [comment]
OK, this version runs correctly for me locally, against the docker image you pushed.

**Comment by tasn** [comment]
This conflicts. Is it now part of that other PR?

**Comment by djmitche** [comment]
It is - #18 was based on the commits in this PR, so merging that PR effectively merged this one.

However, it doesn't look like the actions (clippy or tests) ran on the commits in master, either.

**Comment by djmitche** [comment]
Ah, I see 
> The workflow is not valid. Job clippy depends on unknown job Test.

I'll make a PR for that.

**Comment by tasn** [comment]
OK, so closing this.

**Pull request closed without merging**
